version: "3.9"

services:
  tradingbot:
    build: .
    container_name: ctrader-bot
    restart: unless-stopped
    env_file:
      - .env
    # Montamos todo el directorio para que el bot pueda guardar el refresh_token y detecte los cambios visuales de codigo
    volumes:
      - ./:/app
